console.log(4>3);
console.log(4>=3);
console.log(4<3);
console.log(4<=3);
console.log(4==4);
console.log(4===4);
console.log(4!=4);
console.log(4!==4);
console.log(4!='4');
console.log(4 =='4');
console.log(4==='4');
let a='python';
let b='jargon';
console.log(a.length!=b.length);